import type { ExerciseCard } from './types'

export const cards: ExerciseCard[] = [
  // ---------- Morning ----------
  {
    code: 'M1', name: 'Ankle Pumps and Circles', group: 'M', category: 'Circulation',
    steps: [
      'Stay lying on your back, legs straight.',
      'Point the toes away from you as far as comfortable.',
      'Pull the toes back toward your shin as far as you can.',
      "Repeat briskly 20 times: this is the calf 'pump' that pushes blood back up the leg.",
      'Then draw slow circles with the foot, 10 each way.',
    ],
    holdRepeat: '20 pumps + 10 circles each way, each foot', breath: 'Easy, natural breathing.',
    feel: 'Calf working and a warm feeling in the lower leg.',
    kneeSafety: 'none: this is safe to do many times a day, especially after sitting.',
  },
  {
    code: 'M2', name: 'Heel Slides', group: 'M', category: 'Bend the knee',
    howMuch: '10-15 slides, 2-3 times a day. Only as far as is comfortable.',
    steps: [
      'Lie on your back, legs straight. A sock helps the heel slide.',
      'Slide your heel toward your bottom, bending the knee.',
      'Hold 3-5 seconds.',
      'Slide it all the way back until the knee is fully straight.',
    ],
    feel: 'A stretch in the front of the knee.',
    harder: 'use a towel around your foot to pull gently for the last bit.',
    stopIf: 'the knee catches, locks or has sharp pain. Tell your physio.',
  },
  {
    code: 'M3', name: 'Supta Padangusthasana (with Strap)', group: 'M', category: 'Hamstring stretch',
    steps: [
      'Lie on your back. Bend the good knee with the foot flat on the floor.',
      'Loop a strap around the ball of the injured foot. Hold one end in each hand.',
      'Tighten the thigh to keep the knee straight.',
      'Walk your hands up the strap to raise the leg until you feel a gentle stretch behind the thigh.',
      'Keep the shoulders relaxed on the floor. Hold, then lower slowly with the strap.',
    ],
    holdRepeat: '5-8 breaths x 3 times', breath: 'Breathe out as you raise the leg.',
    feel: 'A stretch in the back of the thigh, not behind the knee joint.',
    kneeSafety: "keep the knee straight and the leg pointing straight up; don't let it roll in or out.",
    easier: 'raise the leg less high.',
    harder: 'after the last hold, let go of the strap and hold the leg up on its own for 2-3 breaths.',
  },
  {
    code: 'M4', name: 'Adho Mukha Svanasana (Downward Dog)', group: 'M', category: 'Calf + hamstring stretch',
    steps: [
      'Start on hands and knees (use a blanket under the knees).',
      'Tuck the toes and lift the hips up and back.',
      'Straighten the legs as much as comfortable; heels reach toward the floor.',
      'Press the hands away and let the head hang between the arms.',
      'To come out, bend the knees and lower them gently. Always step, never jump.',
    ],
    holdRepeat: '5 breaths x 3', breath: 'Long, slow breaths.',
    feel: 'Stretch in the calves and backs of the thighs.',
    kneeSafety: 'if kneeling hurts, do it with the hands on a table or chair seat instead.',
    easier: 'hands on a chair seat.',
  },
  {
    code: 'M5', name: 'Quad Sets', group: 'M', category: 'Most important',
    howMuch: '10 squeezes, hold each 5 seconds. Do this 5-6 times a day.',
    steps: [
      'Sit or lie with your leg straight. Small rolled towel under the knee.',
      'Tighten the front of your thigh. Push the back of the knee down into the towel.',
      'Pull your toes toward you.',
      'Hold for 5 seconds. Relax. Repeat.',
    ],
    feel: 'The thigh muscle goes hard and the kneecap slides up a little.',
    harder: 'hold for 10 seconds.', stopIf: 'sharp pain.',
  },
  {
    code: 'M6', name: 'Flat-Surface Walking', group: 'M', category: 'Walking',
    steps: [
      'Wear cushioned shoes with good grip. Choose a flat, dry, even path (corridor, track, smooth pavement).',
      'Stand tall. Do 5 quick quad squeezes to switch the thigh on.',
      'Walk at a comfortable pace. Land heel first, then roll through to the toes.',
      'Let the knee straighten fully each time the heel touches down.',
      'Keep steps equal on both legs. Swing the arms naturally.',
      'To change direction, turn with several small steps. Never pivot on the injured leg.',
    ],
    holdRepeat: 'Start 15-20 min while swelling settles; add 5 min when the knee is calm, up to 40 min',
    breath: 'Easy breathing; you should be able to talk.',
    feel: 'Warm, loose knee; no limp.',
    kneeSafety: 'stop the walk as soon as you start limping. Avoid grass, gravel, slopes, crowds and wet floors.',
    easier: 'shorter walks, more often.',
    harder: 'add time before speed. Brisk walking only once Phase 1 goals are met. On longer walks, a 1-2 minute standing break halfway is fine.',
  },
  // ---------- Before lunch ----------
  {
    code: 'L1', name: 'Straight-Leg Raises', group: 'L', category: 'Strength',
    howMuch: '3 sets of 10, once or twice a day.',
    steps: [
      'Lie on your back. Bend the good knee, foot flat.',
      'Tighten the thigh of the injured leg so the knee is locked straight.',
      'Lift the leg up to the height of your other knee.',
      'Hold 2 seconds. Lower slowly (count to 3).',
    ],
    feel: 'Work in the front of the thigh and hip.',
    harder: 'add a 0.5 kg ankle weight, and build up slowly to 2-3 kg.',
    stopIf: 'the knee bends as you lift. Go back to quad sets until it stays straight.',
  },
  {
    code: 'L2', name: 'Bridges', group: 'L', category: 'Hips + buttocks',
    howMuch: '3 sets of 10-15.',
    steps: [
      'Lie on your back, knees bent, feet flat.',
      'Squeeze your buttocks and lift your hips.',
      'Stop when shoulders, hips and knees make a straight line.',
      'Hold 3 seconds. Lower slowly.',
    ],
    feel: 'Work in the buttocks and back of the thighs.',
    harder: 'hold 10 seconds, then try on the good leg only.',
    stopIf: 'the lower back hurts. Lift less high.',
  },
  {
    code: 'L3', name: 'Clamshells', group: 'L', category: 'Side of hip',
    howMuch: '3 sets of 10-15 on each side.',
    steps: [
      'Lie on your side, knees bent, feet together.',
      'Keep feet touching. Lift the top knee.',
      "Don't let your body roll backward.",
      'Lower slowly.',
    ],
    feel: 'Work in the side and back of the hip.',
    harder: 'put a stretchy band just above the knees.', stopIf: 'hip or knee pain.',
  },
  {
    code: 'L4', name: 'Side Leg Lifts', group: 'L', category: 'Side of hip',
    howMuch: '3 sets of 10-15 on each side.',
    steps: [
      'Lie on your side. Bend the bottom knee for balance.',
      'Keep the top leg straight, toes pointing forward (not up).',
      'Lift the top leg about a foot (30 cm). Hold 2 seconds.',
      'Lower slowly.',
    ],
    feel: 'Work in the side of the hip.', harder: 'add an ankle weight.',
    stopIf: 'the knee hurts or you feel it in your lower back.',
  },
  {
    code: 'L5', name: 'Heel Prop', group: 'L', category: 'Straighten the knee',
    howMuch: '10 minutes, 3 times a day.',
    steps: [
      'Lie or sit. Put your heel on a rolled towel.',
      'Nothing under the knee. Let it hang.',
      'Relax the thigh completely. Let gravity pull the knee straight.',
      'Every minute, do one quad set to push it a bit more.',
    ],
    feel: 'A gentle stretch behind the knee.',
    harder: 'put a light weight (0.5-2 kg, or a bag of rice) on top of the thigh just above the knee.',
    stopIf: 'strong pain behind the knee.',
  },
  // ---------- Evening ----------
  {
    code: 'E1', name: 'Stationary Bike', group: 'E', category: 'Movement + fitness',
    howMuch: '15-20 minutes, once a day, easy setting.',
    steps: [
      'Set the seat high: the knee is nearly straight when the pedal is at the bottom.',
      "Can't go all the way round yet? Rock back and forth until you can.",
      'Pedal smoothly at an easy pace. You should be able to talk.',
      'Keep your knee pointing forward.',
    ],
    feel: 'Warm, loose knee and light breathing.',
    harder: 'add time first (up to 30 min), then a little resistance. Never stand on the pedals.',
    stopIf: 'pain builds up or the knee swells afterwards.',
  },
  {
    code: 'E2', name: 'Calf Raises', group: 'E', category: 'Calf + circulation',
    howMuch: '3 sets of 15-20, 2-3 times a day.',
    steps: [
      'Stand facing a wall or counter. Hold on lightly.',
      'Weight on both feet.',
      'Rise up onto your toes as high as you can. Hold 2 seconds.',
      'Lower slowly (count to 3).',
    ],
    feel: 'Work in the calf muscles.',
    harder: 'stand on a step with heels hanging off, then try one leg at a time (good leg first).',
    stopIf: 'calf pain, warmth or swelling (see warning box at the end).',
  },
  {
    code: 'E3', name: 'Good-Leg Training', group: 'E', category: 'Keep the other leg strong',
    howMuch: '3 sets of 8-12 of each, once a day or every other day.',
    steps: [
      'Stand up from a chair using only the good leg. Hold the sore leg out in front. Use your hands lightly at first.',
      'Step up onto a low step, good leg first.',
      'Balance on the good leg for 30-60 seconds.',
      'Single-leg calf raises and single-leg bridges on the good leg.',
    ],
    feel: 'The good leg working hard.',
    stopIf: 'the sore leg gets bumped or twisted. Keep it out of the way.',
  },
  {
    code: 'E4', name: 'Vrksasana (Tree) on the Good Leg', group: 'E', category: 'Balance',
    steps: [
      'Stand side-on to a wall. Put the hand nearest the wall on it.',
      'Shift your weight onto the good leg.',
      'Lift the injured leg and rest its sole on the inner calf of the standing leg, never on the knee.',
      'Stand tall, eyes fixed on a point ahead. Other hand at the chest.',
      'Hold, then lower the foot slowly.',
    ],
    holdRepeat: '30-60 seconds x 2', breath: 'Slow, steady breaths.',
    feel: 'The standing leg and hip working to balance.',
    kneeSafety: "don't press the foot hard or twist the injured knee outward; lift it only as far as comfortable.",
    easier: "keep the injured foot's toes on the floor (kickstand).",
    harder: 'take the hand off the wall.',
  },
  {
    code: 'E5', name: 'Supported Utkatasana (Chair Pose at the Wall)', group: 'E', category: 'Quad strength',
    steps: [
      'Stand with your back against a wall, feet hip-width apart and about a foot in front of the wall.',
      'Slide down the wall, bending the knees only a little (30-45 degrees).',
      'Check the knees point over the second toes, not inward.',
      'Keep weight equal on both feet. Arms can reach forward.',
      'Hold, then slide back up.',
    ],
    holdRepeat: '5 breaths x 5', breath: 'Keep breathing smoothly.',
    feel: 'Front of both thighs working.',
    kneeSafety: 'never go deeper than a shallow bend; stop if there is pain at the front of the knee.',
    easier: 'bend even less.', harder: 'hold for 10 breaths.',
  },
  {
    code: 'E6', name: 'Plank', group: 'E', category: 'Tummy + back',
    howMuch: 'Hold 20-30 seconds, 3 times. Build up to 60 seconds.',
    steps: [
      'Lie face down. Rest on your forearms, elbows under shoulders.',
      'Lift your body onto your forearms and toes (or knees, to make it easier).',
      'Keep a straight line from head to heels.',
      'Tighten your tummy. Keep breathing.',
    ],
    feel: 'Work in your tummy muscles.',
    harder: 'hold longer, or try side planks.',
    stopIf: 'your hips sag or your back hurts. Rest, or do it from the knees.',
  },
  {
    code: 'E7', name: 'Side Plank from the Knees', group: 'E', category: 'Core + hip',
    steps: [
      'Lie on your side with the knees bent behind you.',
      'Put the elbow directly under the shoulder, forearm flat on the floor.',
      'Press into the forearm and lift the hips until the body is straight from shoulder to knees.',
      'Reach the top arm toward the ceiling.',
      'Hold, then lower slowly. Change sides.',
    ],
    holdRepeat: '5 breaths x 3, each side', breath: "Steady breathing; don't hold your breath.",
    feel: 'Side of the waist and hip working.',
    kneeSafety: 'if kneeling pressure hurts, put a folded blanket under the knees.',
    easier: 'keep the top hand on the hip.', harder: 'hold for 10 breaths.',
  },
  {
    code: 'E8', name: 'Dead Bug', group: 'E', category: 'Tummy control',
    howMuch: '8-10 each side, 3 times.',
    steps: [
      'Lie on your back. Arms up to the ceiling. Knees bent up at 90 degrees.',
      'Press your lower back gently into the floor.',
      'Slowly stretch out one arm behind you and the opposite leg forward.',
      'Come back. Switch sides.',
    ],
    feel: 'Your tummy working to keep your back still.',
    stopIf: 'your lower back lifts off the floor. Move only the legs to make it easier.',
  },
  {
    code: 'E9', name: 'Ardha Salabhasana (Half Locust)', group: 'E', category: 'Buttocks + hamstrings',
    steps: [
      'Lie face down, forehead resting on the mat or on your folded hands.',
      'Arms by your sides, legs straight, tops of the feet on the floor.',
      'Tighten the thigh of one leg so the knee is straight.',
      'Lift that leg a few centimetres off the floor from the hip.',
      'Hold, then lower slowly. Change legs.',
    ],
    holdRepeat: '5 breaths x 3, each leg', breath: 'Breathe out as you lift.',
    feel: 'Buttock and back of the thigh working.',
    kneeSafety: 'keep the hips pressed down; lift from the hip, not by bending the knee.',
    easier: 'lift only a little.', harder: 'lift both legs together (full locust).',
  },
  {
    code: 'E10', name: 'Viparita Karani (Legs up the Wall)', group: 'E', category: 'Swelling + veins',
    steps: [
      'Sit sideways next to a wall, then swing the legs up the wall as you lie back.',
      'Shuffle the hips close to the wall. Legs rest straight on the wall.',
      'Arms relaxed out to the sides.',
      'Close the eyes and breathe slowly.',
      'To come out, bend the knees, roll onto one side and rest before sitting up.',
    ],
    holdRepeat: '5 minutes', breath: 'Slow belly breathing.',
    feel: 'Legs feel light; swelling drains toward the body.',
    kneeSafety: 'if the hamstrings pull, move the hips a little away from the wall.',
  },
  {
    code: 'E11', name: 'Savasana / Yoga Nidra', group: 'E', category: 'Deep rest',
    steps: [
      'Lie on your back with the roll under the heel of the injured leg, not the knee.',
      'Let the feet fall open, arms slightly away from the body, palms up.',
      'Close the eyes. Move your attention slowly through the body: toes, feet, calves, knees, thighs, all the way to the head.',
      'At each part, let it go heavy and soft.',
      'To finish, roll onto your side and push up slowly.',
    ],
    holdRepeat: '5-10 minutes', breath: "Natural breathing; don't control it.",
    feel: 'Deep relaxation.',
    kneeSafety: 'keep the roll under the heel so the knee keeps straightening while you rest.',
  },
  // ---------- Bands ----------
  {
    code: 'B1', name: 'Terminal Knee Extension (Band)', group: 'B', category: 'Straighten + quad',
    steps: [
      'Tie or anchor the band at knee height to a sturdy post, table leg or a closed door (door anchor on the hinge side).',
      'Loop it behind the injured knee and step back until the band is gently tight.',
      'Stand tall with the injured knee slightly bent, whole foot on the floor. Hold the post for balance.',
      'Push the knee back against the band until it is fully straight. Squeeze the thigh.',
      'Hold 3 seconds, then let the knee bend slowly over 3 counts.',
    ],
    holdRepeat: '2-3 sets of 15, hold 3 sec', breath: 'Out as you straighten.',
    feel: 'Front of the thigh, especially the inner part just above the knee.',
    kneeSafety: "straighten firmly but don't snap the knee back. Keep the heel down and don't twist.",
    easier: 'lighter band or stand closer to the anchor.',
    harder: 'Phase 2: stand on the injured leg only, hand on the post.',
  },
  {
    code: 'B2', name: 'Hamstring Curl (Band)', group: 'B', category: 'Hamstrings',
    steps: [
      'Anchor the band low (door anchor near the floor) behind your feet. Loop the other end round the injured ankle.',
      'Lie face down, forehead on your hands. Slide forward until the band is slightly tight.',
      'Bend the knee, bringing the heel toward the buttock as far as comfortable (about 90 degrees).',
      'Pause for one breath.',
      "Lower slowly over 3 counts. Don't let the band pull the leg down.",
    ],
    holdRepeat: '2-3 sets of 12-15', breath: 'Out as you curl, in as you lower.',
    feel: "Back of the thigh. Strong hamstrings help stop the shin sliding forward, doing part of the ACL's job.",
    kneeSafety: 'stop if you feel cramping or pain behind the knee.',
    easier: 'seated version: sit on a chair, band anchored in front, pull the heel back under the chair.',
    harder: 'thicker band, or hold 3 seconds at the top.',
  },
  {
    code: 'B3', name: 'Lying Leg Press (Band)', group: 'B', category: 'Quad + hip',
    steps: [
      'Lie on your back, good knee bent, foot flat.',
      'Loop the band around the sole of the injured foot. Hold one end in each hand at chest level.',
      'Bring the injured knee toward your chest, only as far as comfortable.',
      'Push the foot away against the band until the knee is fully straight. Squeeze the thigh.',
      'Let the knee bend back slowly over 3 counts.',
    ],
    holdRepeat: '2-3 sets of 12-15', breath: 'Out as you push.',
    feel: 'Front of the thigh and hip working.',
    kneeSafety: "push in a straight line; don't let the knee fall in or out. Stop the bend before any pain.",
    easier: 'lighter band.', harder: 'thicker band, or hold the straight position for 3 seconds.',
  },
  {
    code: 'B4', name: 'Banded Bridge', group: 'B', category: 'Buttocks + side hip',
    steps: [
      'Put a band loop just above both knees.',
      'Lie on your back, knees bent, feet flat and hip-width apart.',
      'Press the knees gently outward against the band.',
      'Squeeze the buttocks and lift the hips into a straight line from shoulders to knees.',
      'Hold 3 seconds, then lower slowly, keeping the knees apart.',
    ],
    holdRepeat: '3 sets of 12, hold 3 sec', breath: 'Out as you lift.',
    feel: 'Buttocks and the sides of the hips working.',
    kneeSafety: 'knees stay in line with the feet; never let them cave in.',
    easier: 'no band.', harder: 'hold 10 seconds, or march small steps at the top.',
  },
  {
    code: 'B5', name: 'Standing Hip Abduction and Kickback (Band)', group: 'B', category: 'Hip strength + balance',
    steps: [
      'Put a band loop around both ankles. Stand side-on to a wall, hand on it.',
      'Put your weight on the good leg, knee soft.',
      'Keeping the injured leg straight and toes forward, move it 20-30 cm out to the side. Return slowly.',
      'Then move it straight back (kickback) 20-30 cm, keeping the body upright. Return slowly.',
      'Both legs work: the moving hip gets stronger, the standing leg works on balance.',
    ],
    holdRepeat: '2 x 12-15 each direction', breath: 'Steady breathing.',
    feel: 'Side and back of the moving hip; balance work in the standing leg.',
    kneeSafety: 'small, slow movements. No leaning or twisting.',
    easier: 'no band, or hold the wall with both hands.',
    harder: 'Phase 2: swap sides so the injured leg is the standing leg (only if the knee is not giving way).',
  },
  {
    code: 'B6', name: 'Lateral Band Walk', group: 'B', category: 'Hips + knee control',
    steps: [
      'Put a band loop just above the knees (easier) or around the ankles (harder).',
      'Feet hip-width apart, knees slightly bent, chest up, hands on hips.',
      'Step 20-30 cm to the side with one foot, then follow with the other. Keep the band tight; feet never touch.',
      'Keep toes pointing forward and knees over the toes.',
      'Take 10 steps one way, then 10 back.',
    ],
    holdRepeat: '10 steps each way, 2-3 rounds', breath: 'Steady breathing.',
    feel: 'Burning in the sides of the hips.',
    kneeSafety: 'start only when walking is normal and the knee is calm. Flat floor, small steps, no crossing feet, no turning.',
    easier: 'band above the knees; smaller steps.',
    harder: 'band around the ankles; deeper knee bend (Phase 2).',
  },
  {
    code: 'B7', name: 'Seated Ankle Push (Band)', group: 'B', category: 'Calf + veins',
    steps: [
      'Sit tall with legs straight (Dandasana). A cushion under the hips helps.',
      'Loop the band around the ball of the injured foot and hold both ends.',
      'Start with the toes pulled back toward you.',
      'Press the foot away against the band, like pressing a car pedal.',
      'Return slowly. Repeat, then switch feet.',
    ],
    holdRepeat: '2-3 sets of 20, each foot', breath: 'Easy breathing.',
    feel: 'Calf working. Each push pumps blood back up the leg, which helps your veins.',
    kneeSafety: 'safe to do often, including after long sitting.',
    harder: 'thicker band.',
  },
  {
    code: 'B8', name: 'Pallof Press (Band)', group: 'B', category: 'Core without twisting',
    steps: [
      'Anchor the band at chest height to a sturdy post or door.',
      'Stand side-on to the anchor, feet hip-width apart, knees soft. Hold the band with both hands at the centre of your chest.',
      'Step away until the band is tight.',
      'Press the hands straight out in front. Hold 3 seconds without letting your body turn toward the anchor.',
      'Bring the hands back slowly. After 10, turn around and do the other side.',
    ],
    holdRepeat: '2 x 10 each side, hold 3 sec', breath: 'Out as you press.',
    feel: 'Deep belly and waist muscles resisting the pull.',
    kneeSafety: 'feet stay planted and the knees stay still. If the knee feels a twist, use a wider stance or a lighter band.',
    easier: 'lighter band or stand closer.', harder: 'hold 5 seconds; stand with feet closer together.',
  },
  // ---------- Getting the bend back ----------
  {
    code: 'K1', name: 'Seated Knee Bend (Foot Slide Back)', group: 'K', category: 'Bend the knee',
    howMuch: '10 reps, 2-3 times a day. Gentle, never forced.',
    steps: [
      'Sit tall on a sturdy chair with both feet flat on the floor.',
      'Slide the foot of the injured leg back under the chair as far as is comfortable. Let the knee bend.',
      'Hold for 10 seconds, breathing out slowly.',
      'Slide the foot forward again to the start. Repeat.',
    ],
    feel: 'A stretch at the front of the knee, and sometimes a fullness behind it.',
    easier: 'slide back less far, or put a sock on the foot so it glides.',
    harder: 'once the foot reaches the chair leg, gently lean the body forward to add a little more bend.',
    stopIf: 'the knee catches, locks or has sharp pain, or it is more swollen afterwards. Do less next time.',
  },
  {
    code: 'K2', name: 'Face-Down Strap Bend', group: 'K', category: 'Bend the knee',
    howMuch: 'Hold 10-20 seconds, 5 reps, once or twice a day.',
    steps: [
      'Lie face down with your forehead on your hands. A cushion under the hips is fine.',
      'Loop a strap around the ankle of the injured leg. Hold the ends in your hands.',
      'Bend the knee, bringing the heel toward your buttock as far as comfortable.',
      'Use the strap to add a very gentle extra pull. Hold 10-20 seconds, then let go slowly.',
    ],
    feel: 'A stretch in the front of the thigh and knee.',
    kneeSafety: 'pull gently. Forcing a swollen knee into a deep bend makes the swelling worse, which then reduces the bend further. Skip this on a swollen day.',
    easier: 'no strap: just let the heel come up on its own.',
    stopIf: 'sharp pain, catching, or the knee is more swollen afterwards.',
  },
  {
    code: 'K3', name: 'Sitting on the Floor Safely', group: 'K', category: 'Daily habits',
    steps: [
      'Sit on a firm cushion or a low stool, 10-15 cm high. Raising the hips reduces how far the knee has to bend.',
      'Keep the injured leg straight out in front, or loosely bent out to the side. Do not tuck it under you or cross your legs.',
      'To get down, hold a wall, a chair or a helper. Lower yourself slowly, taking the weight on the good leg.',
      'To get up, push up through the good leg and your hands. Never twist on the injured knee.',
    ],
    kneeSafety: 'avoid cross-legged sitting, lotus pose and sitting on your heels (vajrasana) for now. They need a very deep bend plus a twist, which a knee without an ACL handles worst.',
    easier: 'sit on a chair instead of the floor for meals and prayers.',
  },
]

export const cardByCode = new Map(cards.map((c) => [c.code, c]))
